-- Shahood Mirza

DROP TABLE INVPROD;
DROP TABLE INVOICE;
DROP TABLE ORDERPROD;
DROP TABLE ORDERS;
DROP TABLE CUSTOMER;
DROP TABLE SALESREP;
DROP TABLE PART;

CREATE TABLE PART
(PARTNO CHAR(4) PRIMARY KEY,
PARTDESC VARCHAR(20),
ONHAND INTEGER,
PARTCLASS CHAR(2) CHECK (PARTCLASS IN ('AP', 'HW', 'KI', 'SP')),
UNITPRICE DECIMAL(6,2)
);

CREATE TABLE SALESREP
(SREPNO CHAR(3),
SREPNAME VARCHAR(25),
SREPSTREET VARCHAR(30),
SREPCITY VARCHAR(15) NOT NULL,
SREPPROV VARCHAR(3) NOT NULL,
SREPPCODE VARCHAR(6) NOT NULL,
TOTCOMM DECIMAL(8,2),
COMMRATE DECIMAL(3,2),
CONSTRAINT PKSLSREP PRIMARY KEY (SREPNO)
);

CREATE TABLE CUSTOMER
(CUSTNO CHAR(3),
CUSTNAME VARCHAR(25) NOT NULL,
CUSTSTREET VARCHAR(30) NOT NULL,
CUSTCITY VARCHAR(15) NOT NULL,
CUSTPROV VARCHAR(3) NOT NULL,
CUSTPCODE VARCHAR(6) NOT NULL,
DISC DECIMAL(3,1),
BALANCE DECIMAL(7,2),
CREDLIMIT DECIMAL(5),
SREPNO CHAR(3),
PRIMARY KEY (CUSTNO),
FOREIGN KEY (SREPNO) REFERENCES SALESREP(SREPNO)
);

CREATE TABLE ORDERS
(ORDERNO CHAR(5) UNIQUE NOT NULL,
ORDERDATE DATE,
CUSTNO CHAR(3) NOT NULL,
CONSTRAINT FKORDERCUST FOREIGN KEY (CUSTNO) REFERENCES CUSTOMER (CUSTNO)
);

CREATE TABLE ORDERPROD
(ORDERNO CHAR(5),
PARTNO CHAR(4),
ORDERQTY INTEGER CHECK (ORDERQTY>0),
ORDERPRICE DECIMAL(7,2),
CONSTRAINT PKORDERPROD PRIMARY KEY (ORDERNO, PARTNO),
CONSTRAINT FK1ORDERPROD FOREIGN KEY (ORDERNO) REFERENCES ORDERS(ORDERNO),
CONSTRAINT FK2ORDERPROD FOREIGN KEY (PARTNO) REFERENCES PART(PARTNO)
);

CREATE TABLE INVOICE
(INVNO CHAR(5) UNIQUE NOT NULL,
INVDATE DATE,
ORDERNO CHAR(5),
PRIMARY KEY (INVNO),
FOREIGN KEY (ORDERNO) REFERENCES ORDERS(ORDERNO)
);

CREATE TABLE INVPROD
(INVNO CHAR(5),
PARTNO CHAR(4),
SHIPQTY INTEGER CHECK (SHIPQTY>0),
PRIMARY KEY (INVNO, PARTNO)
);