-- Shahood Mirza

CREATE INDEX FKPART ON PART(PARTDESC);

CREATE INDEX FKSALESREP ON SALESREP(SREPNAME);

CREATE INDEX FKCUSTOMER ON CUSTOMER(CUSTNAME);

CREATE INDEX FKORDERS ON ORDERS(ORDERDATE);

CREATE INDEX FKORDERPROD ON ORDERPROD(ORDERQTY);

CREATE INDEX FKINVOICE ON INVOICE(INVDATE);

CREATE INDEX FKINVPROD ON INVPROD(SHIPQTY);