-- Shahood Mirza

-- Creating the view
CREATE OR REPLACE VIEW CUSTORDER AS
SELECT DISTINCT CUSTNAME, O.ORDERNO, ORDERDATE, ORDERPRICE * ORDERQTY AS 'TOTAL'
FROM CUSTOMER C, ORDERPROD OP, ORDERS O
WHERE OP.ORDERNO = O.ORDERNO
AND O.CUSTNO = C.CUSTNO;

-- Querying the view for a specific customers information
SELECT * FROM CUSTORDER
WHERE CUSTNAME = 'MIKE';