-- Shahood Mirza

-- UPDATE PRIMARY KEY FILED
-- ALWAYS UPDATE THE PRIMARY KEY TABLE FIRST
-- THEN UPDATE THE CHILD/DETAIL TABLES

INSERT INTO CUSTOMER
(SELECT '777', CUSTNAME, CUSTSTREET, CUSTCITY, CUSTPROV,
CUSTPCODE, DISC, BALANCE, CREDLIMIT, SREPNO
FROM CUSTOMER
WHERE CUSTNO='104');

UPDATE ORDERS
SET CUSTNO='777'
WHERE CUSTNO='104';

-- DELETE RECORD FROM CUSTOMER TABLE
DELETE FROM CUSTOMER
WHERE CUSTNO='104';