-- Shahood Mirza

-- SIMPLE INNER JOIN

SELECT C.CUSTNO, CUSTNAME, ORDERNO, ORDERDATE
   FROM CUSTOMER C, ORDERS O
      WHERE C.CUSTNO = O.CUSTNO;

-- LEFT OUTER JOIN
SELECT C.CUSTNO, CUSTNAME, ORDERNO, ORDERDATE
   FROM CUSTOMER C LEFT OUTER JOIN ORDERS O
      ON C.CUSTNO = O.CUSTNO;

-- DISPLAY ALL THE PARTS FROM THE PART TABLE AND SHOW IF THEY HAVE BEEN ORDERED AT ALL

SELECT P.PARTNO, PARTDESC, PARTCLASS, ORDERNO
   FROM PART P LEFT OUTER JOIN ORDERPROD OP
      ON P.PARTNO = OP.PARTNO;

-- DISPLAY ALL CUSTOMERS AND ANY SALESREP INFO THAT HAVE BEEN ASSOCIATED WITH CUSTOMERS

SELECT CUSTNO, CUSTNAME, CUSTCITY, C.SREPNO, SREPNAME
   FROM CUSTOMER C RIGHT OUTER JOIN SALESREP S
      ON C.SREPNO - S.SREPNO;

SELECT CUSTNO, CUSTNAME, CUSTCITY, C.SREPNO, SREPNAME
   FROM CUSTOMER S LEFT OUTER JOIN CUSTOMER C
      ON C.SREPNO - S.SREPNO;

