-- Shahood Mirza

-- DISPLAY ALL CUSTOMERS WHO LIVE IN MISSISSAUGA
SELECT * FROM CUSTOMER
WHERE CUSTCITY = 'MISSUSSAUGA';

SELECT CUSTNO, CUSTOMER
FROM CUSTOMER;

-- DISPLAY ALL CUSTOMERS WHO LIVE IN MISSISSAUGA OR BRAMPTON
SELECT * FROM CUSTOMER
WHERE CUSTCITY = 'MISSISSAUGA'
OR CUSTCITY = 'BRAMPTON';

-- DISPLAY PARTS THAT ARE IN HARDWARE SECTION
SELECT * FROM PART 
WHERE PARTCLASS = UPPER('HW')
OR PARTCLASS = UPPER('KI');

-- DISPLAY PARTS THAT HAVE UNITPRICE GREATER THAN $10.00
SELECT * FROM PART
WHERE UNITPRICE > 10;

SELECT * FROM PART
WHERE UNITPRICE BETWEEN 20 AND 10;

-- DISPLAY ORDERS THAT WERE BEFORE A CERTAIN DATE
SELECT * FROM ORDERS
WHERE ORDERDATE < '2011-12-25';

-- DISPLAYING NULL VALUES
SELECT * FROM PART
WHERE PARTCLASS IS NOT NULL;

-- DISPLAYING PARTS STARTING WITH 'T' (%T FOR ENDING WITH 'T') --> % MEANS ANY NUMBER OF CHARACTERS
SELECT * FROM PART
WHERE PARTDESC LIKE 'T%';

-- DISPLAYING PARTS WHERE THE SECOND LETTER IS 'O' --> _ MEANS ONLY ONE CHARACTER
SELECT * FROM PART
WHERE PARTDESC LIKE '_O%';


SELECT * FROM PART
ORDER BY PARTCLASS, PARTDESC;

-- JOINS
-- CARTESIAN PRODUCT/CARTESIAN JOIN

SELECT * FROM CUSTOMER, ORDERS;

-- DISPLAY CUSTOMER INFO THAT HAVE PLACED ORDERS
SELECT C.CUSTNO, CUSTNAME, CUSTCITY, ORDERDATE, ORDERNO
FROM CUSTOMER C, ORDERS O
WHERE O.CUSTNO = C.CUSTNO;

-- DISPLAY WHAT WAS ORDERED BY EACH CUSTOMER (INNER JOIN: ORDERS & ORDERPROD, PART & ORDERPROD AND CUSTOMER & ORDER)
SELECT P.PARTNO, P.PARTDESC, P.PARTCLASS, O.ORDERNO, C.CUSTNO, CUSTNAME, CUSTCITY
FROM ORDERS O, CUSTOMER C, ORDERPROD OP, PART P
WHERE O.ORDERNO = OP.ORDERNO
AND P.PARTNO = OP.PARTNO
AND C.CUSTNO = O.CUSTNO;

SELECT P.PARTNO, P.PARTDESC, P.PARTCLASS, O.ORDERNO, C.CUSTNO, CUSTNAME, CUSTCITY
FROM ORDERS O INNER JOIN CUSTOMER C
ON C.CUSTNO = O.CUSTNO
INNER JOIN ORDERPROD OP
ON O.ORDERNO = OP.ORDERNO
INNER JOIN PART P ON P.PARTNO = OP.PARTNO;